### PR TITLE
this PR contains 2 pages: manage user and manage product

### PR DESCRIPTION
**Pull request by VietNNSE161326**

### CODE REVIEW

**Comment by VietNNSE161326** [comment]
image
Manage User view

**Comment by VietNNSE161326** [comment]
image
Edit user modal

**Comment by VietNNSE161326** [comment]
image
Manage Product view

**Comment by VietNNSE161326** [comment]
image
Edit Product modal

**Review by mantvse15 — APPROVED** [review]
lgtm

**Pull request merged**
